builds:
  - binary: price
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - 
    name: price
    homepage: https://github.com/inuoshios/price-action
    tap:
      owner: inuoshios
      name: homebrew-inuoshios
    commit_author:
      name: inuoshios
      email: inuoshios@gmail.com

checksum:
  name_template: 'price_v1_checksums.txt'

  