project_name: price

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - binary: price
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  use: github
  sort: asc

  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo

signs:
  - signature: "price.msi"
    cmd: ./signtool
    args:
      - "${signature}"
      - "${artifact}"
    artifacts: all
    ids:
      - "windows"

brews:
  - name: price
    homepage: https://github.com/ixxiv/price-action
    tap:
      owner: ixxiv
      name: homebrew-ixxiv
    commit_author:
      name: ixxiv
      email: inuoshios@gmail.com

checksum:
  name_template: "price_v1_checksums.txt"
